COPY public."Badge" (id, title, description, "iconUrl", condition, "createdAt", "updatedAt") FROM stdin;
COPY public."Chapter" (id, "courseId", title, subtitle, "orderIndex", "timeLimit", "isVisible", "isFinalExam", "createdAt", "updatedAt", "taskId", "releaseTime", content) FROM stdin;
COPY public."Comment" (id, "postId", "userId", content, "createdAt", "updatedAt", "isVisible") FROM stdin;
COPY public."Course" (id, title, description, level, "gemCost", "rankRequired", "levelRequired", "createdAt", "updatedAt", "archivedAt", "excellentScore", "isArchived", "isPublished", "passingScore", "publishedAt", thumbnail, "timeLimit") FROM stdin;
COPY public."DailyMission" (id, title, description, "gemReward", "expReward", type, requirement, "createdAt", "updatedAt") FROM stdin;
COPY public."ForumPost" (id, "userId", title, content, likes, "createdAt", "updatedAt", "isVisible") FROM stdin;
COPY public."LevelMessage" (id, level, message, "isActive", "createdAt", "updatedAt") FROM stdin;
COPY public."Mission" (id, title, description, "missionType", duration, conditions, "isActive", "startDate", "endDate", "createdAt", "updatedAt") FROM stdin;
COPY public."MissionReward" (id, "missionId", gems, exp, "createdAt", "updatedAt") FROM stdin;
COPY public."Product" (id, name, description, type, price, "gemAmount", "courseId", "rankRequired", "levelRequired", "isActive", "createdAt", "updatedAt") FROM stdin;
COPY public."Purchase" (id, "userId", "productId", amount, "totalPrice", status, "createdAt", "updatedAt") FROM stdin;
COPY public."Submission" (id, "userId", "taskId", content, points, feedback, "submittedAt", "evaluatedAt") FROM stdin;
COPY public."Task" (id, "courseId", title, description, "maxPoints", "createdAt", "updatedAt", "referenceText", "systemMessage") FROM stdin;
COPY public."TokenTracking" (id, "userId", "weeklyTokens", "unprocessedTokens", "lastSyncedAt", "createdAt", "updatedAt", "purchasedTokens", "weeklyLimit") FROM stdin;
COPY public."User" (id, email, password, name, level, experience, gems, "createdAt", "updatedAt", status, "mongoId", nickname, "snsLinks", "isRankingVisible", "isProfileVisible", message, "avatarUrl", rank) FROM stdin;
COPY public."UserBadge" (id, "userId", "badgeId", "earnedAt") FROM stdin;
COPY public."UserChapterProgress" (id, "userId", "courseId", "chapterId", status, "startedAt", "completedAt", score, "createdAt", "updatedAt") FROM stdin;
COPY public."UserCourse" (id, "userId", "courseId", progress, "startedAt", "completedAt", status, "isActive") FROM stdin;
COPY public._prisma_migrations (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) FROM stdin;
